# This is a basic workflow to help you get started with Actions

name: On Issue New Comment

# Controls when the action will run. Triggers the workflow when a new issue COMMENT is created (on an ALREADY OPENED issue)
# but only for the master branch
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
    - name: print $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run:
        echo "$GITHUB_CONTEXT"
    - name: exctract something from github context
      env:
        COMMENT: ${{ toJson(github['event']['comment']) }}
      run: |
        echo "$COMMENT"
        echo "issue id ${{ github.event.issue.number }}"
    - name: Create new comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hello @${{ github.actor }}! :smile:

          With more reactions now. :tada:

        reactions: eyes, heart, laugh