# This is a basic workflow to help you get started with Actions

name: On Issue New Comment

# Controls when the action will run. Triggers the workflow when a new issue COMMENT is created (on an ALREADY OPENED issue)
# but only for the master branch
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: print $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run:
        echo "$GITHUB_CONTEXT"
    - name: exctract something from github context
      run:
        echo "$GITHUB_CONTEXT"
