# This is a basic workflow to help you get started with Actions

name: On Issue New Comment

# Controls when the action will run. Triggers the workflow when a new issue COMMENT is created (on an ALREADY OPENED issue)
# but only for the master branch
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: print $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run:
        echo "$GITHUB_CONTEXT"
    - name: exctract something from github context
      env:
        COMMENT: ${{ toJson(github['event']['comment']) }}
      run: |
        echo "$COMMENT"
        echo "issue id ${{ github.event.issue.number }}"
    - name: Create new comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hello @${{ github.actor }}! :smile:

          This is a wonderful markdown test comment
          - Created by [many][1]

          [1]: https://github.com/azrafe7/grab_and_process_data_via_github_actions/blob/master/NOTES.md
        reactions: 'eye'