# This is a basic workflow to help you get started with Actions

name: On New Issue Creation

# Controls when the action will run. Triggers the workflow when a new issue is opened, but only for the master branch
on:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
    - name: print $github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run:
        echo "$GITHUB_CONTEXT"

